# This is a basic workflow to help you get started with Actions

name: CI-self-hosted

on:
  push:
    branches: [ main ]
env:
  app_pool_name: partsnew
  app_name: newparts

jobs:
  Build:
    runs-on: test-app
    steps:
    - name: Checkout the source code
      uses: actions/checkout@v2

    - name: Run Powershell
      run: |
        & '${{github.workspace}}\app.ps1' -pool_name ${{env.app_pool_name}} -app_name ${{env.app_name}}
